### ISSUE TITLE
Packages Needed

### ISSUE THREAD

**Issue by gorlapraveen** [edwardoughton/itmlogic#34]
`Traceback (most recent call last):
  File "scripts/p2p.py", line 28, in <module>
    from terrain_module import terrain_p2p
  File "/itmlogic/scripts/terrain_module.py", line 21, in <module>
    from rasterstats import gen_zonal_stats, point_query
ModuleNotFoundError: No module named 'rasterstats'
`

To suppress this Error need to add `rasterstats` and `simplejson` packages installation through conda/pip . And these are not optional as I observed to test p2p mode script.

**Comment by danielskatz** [comment]
found in JOSS review https://github.com/openjournals/joss-reviews/issues/2266

**Comment by edwardoughton** [comment]
I have now added both packages to the conda install / pip reqs, and then tested with a clean install. This should now be solved.
