### ISSUE TITLE
Missing links to online documentation

### ISSUE THREAD

**Issue by garrettj403** [edwardoughton/itmlogic#36]
I see that there is some online documentation for the ``itmlogic`` project (hosted at: https://itmlogic.readthedocs.io/en/latest/), but there aren't any links to this page from the GitHub repo.

Could you please add a link to this page in README? 

You can also list this webpage under the short description of your GitHub repo:

<img width="997" alt="example" src="https://user-images.githubusercontent.com/14835953/84524406-f0577200-aca7-11ea-8318-04befa667e43.png">

**Comment by garrettj403** [comment]
Note: This is part of my review for JOSS [#2266](https://github.com/openjournals/joss-reviews/issues/2266).

**Comment by edwardoughton** [comment]
Thanks for this, I've now added in the url to both the website box, and also added a documentation section in the readme linking to the readthedocs.
