### ISSUE TITLE
NaN in Tif file

### ISSUE THREAD

**Issue by soramarcos** [edwardoughton/itmlogic#42]
Hi, first of all thank you for writing this code and sharing it!

I'm quite new to using Python for spatial analysis so I might be missing something basic. I'm trying to run your p2p code and I'm getting trouble when using the terrain module.

I've downloaded the .TIF which includes the area I'm interested in, in Northern Argentina, from ALOS website. When I run the p2p file I'm getting an error related to the terrain module file. In particular, the error is coming when the code calculates the number of samples. I suspect I'm getting a distance_m = NaN. 

Is there an easy way to check + solve this? 

Thanks!

**Comment by edwardoughton** [comment]
@tomalrussell any ideas?

@soramarcos can you confirm you have the correct coordinate reference system and then post more details, such as a reproducible example?

**Comment by soramarcos** [comment]
Hi @edwardoughton, thanks for answering and sorry for the delay! In effect I was not using the correct coordinate reference system. I'll fix that.

**Comment by edwardoughton** [comment]
@soramarcos okay, great, I'm going to close this issue.
