### ISSUE TITLE
Additional comments in example scripts

### ISSUE THREAD

**Issue by garrettj403** [edwardoughton/itmlogic#43]
I'm having a hard time following the examples in the ``scripts/`` directory. Could you please add a few more inline comments? For example, ``scripts/area.py`` doesn't have any comments past line 107.

You may also want to consider adding a quick script to plot the results. 

Note that there's a typo in README on line 71: ``scripts/uarea.py`` should be ``scripts/area.py``.

**Comment by edwardoughton** [comment]
@garrettj403 thanks for the detailed review, I'm going to turn this around by the weekend.

**Comment by edwardoughton** [comment]
@garrettj403 Comments have now been added throughout both runner scripts (scripts/area.py and scripts/p2p.py), and doc strings have been improved throughout all modules and tests. We have also added visualized results to the readme, and provide all the code in the repo folder vis/vis.py for producing these plots. I also removed the typo you mentioned - thanks for catching that.
