### ISSUE TITLE
Docstrings for tests

### ISSUE THREAD

**Issue by garrettj403** [edwardoughton/itmlogic#44]
It's very difficult to follow what the tests are testing. 

For example, in ``test_lrprop.py``, where does ``setup_expected_prop_to_test_lrprop`` come from? Were these results generated by the previous FORTRAN/C++/MATLAB code? 

It would be helpful to have short docstrings broadly describing each test.

**Comment by edwardoughton** [comment]
@garrettj403 Doc strings have now been improved throughout all modules and tests. Where we have a direct reference for an equation in the references documentation, we have been explicit about it. Hopefully this makes things a bit clearer now.
