### ISSUE TITLE
Coveralls not working

### ISSUE THREAD

**Issue by edwardoughton** [edwardoughton/itmlogic#7]
- [x] get tests to pass locally
- [x] get tests to pass on travis (https://travis-ci.org/edwardoughton/itmlogic/builds)
- [x] configure coveralls and check it receives jobs (https://coveralls.io/github/edwardoughton/itmlogic)

**Comment by tomalrussell** [comment]
Closed by 52315e7b8fb226f555dfad86aebb2f5530cd4487
